name: Build and attest image

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  attestations: write

env:
  REGISTRY: europe-west1-docker.pkg.dev
  IMAGE_NAME: test-provenance/test-container
  GCP_PROJECT_ID: main-entropy-469304-f4
  GCP_WIP: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GCP Auth
        id: gcp_auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: "projects/371170618631/locations/global/workloadIdentityPools/ghpool/providers/github-provider"
          service_account: gha-cloudrun-deployer@main-entropy-469304-f4.iam.gserviceaccount.com

      - name: Configure Docker to use gcloud for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: europe-west1-docker.pkg.dev/test-provenance/test-container:latest

      - name: Delete Docker config
        run: rm -f ~/.docker/config.json

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.gcp_auth.outputs.auth_token }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: europe-west1-docker.pkg.dev/test-provenance/test-container
          subject-digest: ${{ steps.docker_build_push.outputs.digest }}
          push-to-registry: true