name: Build and attest image

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  attestations: write

env:
  REGISTRY: europe-west1-docker.pkg.dev
  IMAGE_NAME: main-entropy-469304-f4/test-provenance/test-container
  GCP_PROJECT_ID: main-entropy-469304-f4
  GCP_WIP: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: projects/371170618631/locations/global/workloadIdentityPools/ghpool/providers/github-provider

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}

      - name: Print OIDC token using github-script
        uses: actions/github-script@v7
        with:
          script: |
            const token = await github.rest.actions.getWorkflowRunAttempt({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              attempt_number: 1
            });
            console.log(token);

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: europe-west1-docker.pkg.dev/main-entropy-469304-f4/test-provenance/test-container:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: europe-west1-docker.pkg.dev/main-entropy-469304-f4/test-provenance/test-container
          subject-digest: ${{ steps.docker_build_push.outputs.digest }}
          push-to-registry: true