name: Create and attest File

on:
  workflow_dispatch:

jobs:
  create-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Create test file
        run: echo "TEST" > test.txt

      - name: Generate provenance attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'test.txt'
